apiVersion: apps/v1
kind: Deployment
metadata:
  name: scalable-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: scalable-webapp
  template:
    metadata:
      labels:
        app: scalable-webapp
    spec:
      containers:
      - name: scalable-webapp
        image: scalable-webapp  # local Docker image
        imagePullPolicy: Never  # use local image without pulling
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: scalable-webapp-service
spec:
  type: NodePort
  selector:
    app: scalable-webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30036
